version: '3.8'
services:
    apache:
        image: httpd:alpine
        container_name: 'Apache'
        ports:
            - 80:80
        volumes:
            - ./htdocs:/usr/local/apache2/htdocs/
        networks:
            - padrao
networks:
    padrao:
        driver: bridge